variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: ""

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/

test backend:
  stage: test
  image: maven:3.5.2-jdk-8
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  tags:
    - mvn
    - jdk-8

test frontend:
  stage: test
  image: node:8
  script:
    - cd ./src/main/webapp/WEB-INF/view/react
    - npm install
    - npm run-script test
  artifacts:
    reports:
      junit:
        - ./src/main/webapp/WEB-INF/view/react/junit.xml
        - ./src/main/webapp/WEB-INF/view/react/coverage
  tags:
    - node

build frontend:
  stage: build
  image: node:8
  script:
    - cd ./src/main/webapp/WEB-INF/view/react
    - npm install
    - unset CI
    - npm run-script build
    - mv httpd.conf ./build/
    - mv dockerfile ./build/
    - mv .dockerignore ./build/
  artifacts:
    paths:
    - src/main/webapp/WEB-INF/view/react/build/
    expire_in: 5 mins
  only:
    - /^master*$/
  tags:
    - node
    
deploy frontend:
  stage: deploy
  image: docker:latest
  dependencies:
    - build frontend
  script:
    - docker rm -f rate_the_movie_fe 2>/dev/null || true
    - cd ./src/main/webapp/WEB-INF/view/react/build
    - docker build -f dockerfile -t ratethemovie_fe:0.0.1 .
    - docker run -d -p 0.0.0.0:80:80 --net=host --name rate_the_movie_fe ratethemovie_fe:0.0.1
  only:
    - /^master*$/
  tags:
    - deploy
  
deploy backend:
  stage: deploy
  image: docker:stable
  dependencies: []
  before_script:
    - docker info
  script:
    - docker rm -f rate_the_movie 2>/dev/null || true
    - docker build -f dockerfile -t ratethemovie:0.0.1 .
    - docker run -d -p 0.0.0.0:8080:8080 --net=host --name rate_the_movie ratethemovie:0.0.1
  only:
    - /^master*$/
  tags:
    - deploy
